services:
  todolist-postgres:
    image: postgres:18.4-alpine
    container_name: todolist-postgres
    environment:
      - POSTGRES_DB=${DATABASE_POSTGRES_DB}
      - POSTGRES_USER=${DATABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    ports:
      - "${DATABASE_POSTGRES_PORT}:5432"
    restart: always
  
  todolist-postgres-migrate:
    image: migrate/migrate:v4.19.1
    container_name: todolist-postgres-migrate
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
    depends_on:
      - todolist-postgres